(function(n){function g(e,a,l,h){if("string"!=typeof e)throw"System.register provided no module name";a="boolean"==typeof l?{declarative:!1,deps:a,execute:h,executingRequire:l}:{declarative:!0,deps:a,declare:l};a.name=e;e in q||(q[e]=a);e=a.deps;l=[];h=0;for(var c=e.length;h<c;h++)-1==m.call(l,e[h])&&l.push(e[h]);a.deps=l;a.normalizedDeps=a.deps}function f(e,a){a[e.groupIndex]=a[e.groupIndex]||[];if(-1==m.call(a[e.groupIndex],e)){a[e.groupIndex].push(e);for(var h=0,c=e.normalizedDeps.length;h<c;h++){var b=
q[e.normalizedDeps[h]];if(b&&!b.evaluated){var d=e.groupIndex+(b.declarative!=e.declarative);if(void 0===b.groupIndex||b.groupIndex<d){if(void 0!==b.groupIndex&&(a[b.groupIndex].splice(m.call(a[b.groupIndex],b),1),0==a[b.groupIndex].length))throw new TypeError("Mixed dependency cycle detected");b.groupIndex=d}f(b,a)}}}}function b(e){return u[e]||(u[e]={name:e,dependencies:[],exports:{},importers:[]})}function d(e){if(!e.module){var a=e.module=b(e.name),c=e.module.exports,k=e.declare.call(n,function(e,
h){a.locked=!0;c[e]=h;for(var b=0,k=a.importers.length;b<k;b++){var q=a.importers[b];if(!q.locked){var d=m.call(q.dependencies,a);q.setters[d](c)}}a.locked=!1;return h});a.setters=k.setters;a.execute=k.execute;if(!a.setters||!a.execute)throw new TypeError("Invalid System.register form for "+e.name);for(var k=0,f=e.normalizedDeps.length;k<f;k++){var g=e.normalizedDeps[k],r=q[g],p=u[g];p?g=p.exports:r&&!r.declarative?g=r.module.exports&&r.module.exports.__esModule?r.module.exports:{"default":r.module.exports,
__useDefault:!0}:r?(d(r),p=r.module,g=p.exports):g=h(g);p&&p.importers?(p.importers.push(a),a.dependencies.push(p)):a.dependencies.push(null);if(a.setters[k])a.setters[k](g)}}}function c(e){if(!e.module){var b={},l=e.module={exports:b,id:e.name};if(!e.executingRequire)for(var k=0,m=e.normalizedDeps.length;k<m;k++){var d=q[e.normalizedDeps[k]];d&&c(d)}e.evaluated=!0;if(b=e.execute.call(n,function(b){for(var l=0,k=e.deps.length;l<k;l++)if(e.deps[l]==b){b=e.normalizedDeps[l];l=void 0;if(k=q[b])k.declarative?
a(b,[]):k.evaluated||c(k),l=k.module.exports;else if(l=h(b),!l)throw Error("Unable to load dependency "+b+".");b=(!k||k.declarative)&&l&&l.__useDefault?l["default"]:l;return b}throw new TypeError("Module "+b+" not declared as a dependency.");},b,l))l.exports=b}}function a(e,b){var l=q[e];if(l&&!l.evaluated&&l.declarative){b.push(e);for(var c=0,d=l.normalizedDeps.length;c<d;c++){var f=l.normalizedDeps[c];-1==m.call(b,f)&&(q[f]?a(f,b):h(f))}l.evaluated||(l.evaluated=!0,l.module.execute.call(n))}}function h(e){if(p[e])return p[e];
var b=q[e];if(!b)throw"Module "+e+" not present.";var h=q[e];h.groupIndex=0;var k=[];f(h,k);for(var h=!!h.declarative==k.length%2,m=k.length-1;0<=m;m--){for(var g=k[m],u=0;u<g.length;u++){var n=g[u];h?d(n):c(n)}h=!h}a(e,[]);q[e]=void 0;k=b.module.exports;if(!k||!b.declarative&&!0!==k.__esModule)k={"default":k,__useDefault:!0};return p[e]=k}var q={},m=Array.prototype.indexOf||function(a){for(var b=0,h=this.length;b<h;b++)if(this[b]===a)return b;return-1},u={},p={};return function(a,b){var c;c={register:g,
get:h,set:function(a,b){p[a]=b},newModule:function(a){return a},global:n};c.set("@empty",{});b(c);for(c=0;c<a.length;c++)h(a[c])}})("undefined"!=typeof window?window:global)(["background-exports"],function(n){n.register("crypto",[],function(g){var f;g("generateKey",function(){return f.subtle.generateKey({name:"AES-GCM",length:256},!0,["encrypt","decrypt"])});g("exportKey",function(b){return f.subtle.exportKey("jwk",b)});g("importKey",function(b){return f.subtle.importKey("jwk",b,{name:"AES-GCM"},
!0,["encrypt","decrypt"])});g("encrypt",function(b,d){var c=window.crypto.getRandomValues(new Uint8Array(16)),a=new Uint8Array(0);return f.subtle.encrypt({name:"AES-GCM",iv:c,additionalData:a,tagLength:128},d,b).then(function(b){return[c,a,b]})});g("decrypt",function(b,d){return f.subtle.decrypt({name:"AES-GCM",iv:b[0],additionalData:b[1],tagLength:128},d,b[2])});return{setters:[],execute:function(){f=window.crypto}}});n.register("bg-storage-service",[],function(g){function f(){c||(c=new d);return c}
var b,d,c;return{setters:[],execute:function(){b={set:function(a,b){return new Promise(function(c,m){var d;chrome.storage.local.set((d={},Object.defineProperty(d,a,{value:b,configurable:!0,enumerable:!0,writable:!0}),d),function(){if(chrome.runtime.lastError)return m(chrome.runtime.lastError);c()})})},get:function(a,b){return new Promise(function(c,m){chrome.storage.local.get(a,function(d){if(chrome.runtime.lastError)return m(chrome.runtime.lastError);c(d.hasOwnProperty(a)?d[a]:b)})})}};d=function(){function a(){return $traceurRuntime.asyncWrap(function(a){for(;;)switch(a.state){case 0:f=
b.get("cfDraw_store",{});a.state=5;break;case 5:Promise.resolve(f).then(a.createCallback(3),a.errback);return;case 3:g=a.value;a.state=-2;break;default:return a.end()}},this)}function c(a){a&&"castifyDrawStore"===a.type&&(g=a.data,b.set("cfDraw_store",g));return!1}var d={},m=!1,f=null,g;d.getData=function(){return $traceurRuntime.asyncWrap(function(a){for(;;)switch(a.state){case 0:Promise.resolve(f).then(a.createCallback(2),a.errback);return;case 2:a.returnValue=g;a.state=4;break;case 4:a.state=-2;
break;default:return a.end()}},this)};d.start=function(){m||(m=!0,chrome.runtime.onMessage.addListener(c),a())};d.stop=function(){m&&(m=!1,chrome.runtime.onMessage.removeListener(c))};return d};c=null;g("getBgStorageService",f)}}});n.register("chrome-messaging",[],function(g){function f(b){return b instanceof Error?Promise.reject(b.toString()):Promise.reject(b)}g("sendMessage",function(b,d){return new Promise(function(c,a){chrome.runtime.sendMessage({type:b,data:d},function(b){chrome.runtime.lastError?
a(chrome.runtime.lastError):b?"result"===b.type?c(b.data):"error"===b.type&&a(b.data):a()})})});g("respond",function(b,d){Promise.resolve(d).catch(f).then(function(c){b({type:"result",data:c})},function(c){b({type:"error",data:c})})});return{setters:[],execute:function(){}}});n.register("w69b/q",[],function(g){var f;return{setters:[],execute:function(){f={defer:function(){var b={};b.promise=new Promise(function(d,c){b.resolve=d;b.reject=c});return b}};f.when=Promise.resolve.bind(Promise);f.all=Promise.all.bind(Promise);
f.reject=Promise.reject.bind(Promise);Promise.prototype.finally||(Promise.prototype.finally=function(b){var d=this.constructor;return this.then(function(c){return d.resolve(b()).then(function(){return c})},function(c){return d.resolve(b()).then(function(){throw c;})})});g("default",f)}}});n.register("throttle",[],function(g){function f(b,d,c){var a,h,f;c=!1!==c;var m=function(){f=Object.assign([],arguments);h=function(){h=a=null;return b.apply(null,f)};c?(a&&window.clearTimeout(a),a=window.setTimeout(h,
d)):a||(a=window.setTimeout(h,d))};m.flush=function(){a&&(window.clearTimeout(a),h())};m.cancel=function(){a&&window.clearTimeout(a)};return m}return{setters:[],execute:function(){g("default",f)}}});n.register("bg-message-service",["crypto"],function(g){function f(){c||(c=new d);return c}var b,d,c;return{setters:[function(a){b=a}],execute:function(){d=function(){function a(a,b,e){if(!a)return!1;if("castifyDrawGetMsgKey"===a.type){if(b.tab.url.startsWith("https://"))return c.then(function(a){e(a)}).catch(function(){e(null)}),
!0;e("plain")}else if("castifyDrawFrameBroadcast"===a.type&&b.tab)chrome.tabs.sendMessage(b.tab.id,a.data);else if("castifyDrawFrameMsgWithResult"===a.type&&b.tab)return chrome.tabs.sendMessage(b.tab.id,a.data,e),!0;return!1}var c=b.generateKey().then(b.exportKey),d={},m=!1;d.start=function(){m||(chrome.runtime.onMessage.addListener(a),m=!0)};d.stop=function(){m&&(m=!1,chrome.runtime.onMessage.removeListener(a))};return d};c=null;g("getBgMessageService",f)}}});n.register("w69b/promise-tool",["w69b/q"],
function(g){var f,b;return{setters:[function(b){f=b.default}],execute:function(){b={wrapChromeError:function(b,c){return function(){var a=Array.prototype.slice.call(arguments,0),h=f.defer();a.push(function(a){chrome.runtime.lastError?h.reject(chrome.runtime.lastError):h.resolve(a)});b.apply(c,a);return h.promise}},wrapCallbacks:function(b,c){return function(){var a=Array.prototype.slice.call(arguments,0),h=f.defer();a.push(h.resolve.bind(h));a.push(h.reject.bind(h));b.apply(c,a);return h.promise}}};
g("default",b)}}});n.register("w69b/webrtc",["w69b/promise-tool","w69b/q"],function(g){function f(a){return a.some(function(a){return!!a.label})}var b,d,c,a;return{setters:[function(a){b=a.default},function(a){d=a.default}],execute:function(){c={};a=window.navigator;c.getUserMedia=a.mediaDevices&&a.mediaDevices.getUserMedia?a.mediaDevices.getUserMedia.bind(a.mediaDevices):b.wrapCallbacks(a.getUserMedia||a.webkitGetUserMedia||a.mozGetUserMedia||a.msGetUserMedia,a);c.getSources=a.mediaDevices&&a.mediaDevices.enumerateDevices?
function(){return d.when(a.mediaDevices.enumerateDevices()).then(function(a){return a.filter(function(a){return a.kind.endsWith("input")}).map(function(a){var b={id:a.deviceId,label:a.label};b.kind=a.kind.substring(0,a.kind.length-5);return b})})}:window.MediaStreamTrack&&MediaStreamTrack.getSources?b.wrapCallbacks(MediaStreamTrack.getSources,MediaStreamTrack):function(){return Promise.resolve([])};c.getSourcesByKind=function(a){return c.getSources().then(function(b){return b.filter(function(b){return b.kind===
a})})};c.getVideoSources=function(){return c.getSourcesByKind("video")};c.getAudioSources=function(){return c.getSourcesByKind("audio")};c.hasCamera=function(){return c.getVideoSources().then(function(a){return 0<a.length})};c.hasMicrophone=function(){return c.getAudioSources().then(function(a){return 0<a.length})};c.hasVideoAccess=function(){return c.getVideoSources().then(f)};c.hasAudioAccess=function(){return c.getAudioSources().then(f)};g("default",c)}}});n.register("bg-cam-sustain-service",["chrome-messaging",
"w69b/webrtc"],function(g){function f(){a||(a=new c);return a}var b,d,c,a;return{setters:[function(a){b=a},function(a){d=a.default}],execute:function(){c=function(){function a(){p&&(p.getTracks().forEach(function(a){a.stop()}),e=p=null)}function c(a,e,d){return a&&"castifyDrawCamSustainMsg"===a.type&&(a=a.data)&&n.hasOwnProperty(a.type)?(b.respond(d,n[a.type](a.data)),!0):!1}var f={},g=!1,p,e,n={start:function(b){return $traceurRuntime.asyncWrap(function(c){for(;;)switch(c.state){case 0:c.state=p?
4:6;break;case 4:c.state=JSON.stringify(e)===JSON.stringify(b)?1:3;break;case 1:c.returnValue=void 0;c.state=2;break;case 2:c.state=-2;break;case 3:a();c.state=6;break;case 6:Promise.resolve(d.getUserMedia({video:b})).then(c.createCallback(10),c.errback);return;case 10:p=c.value;c.state=9;break;case 9:e=b;c.state=-2;break;default:return c.end()}},this)},stop:function(){a()}};f.start=function(){g||(chrome.runtime.onMessage.addListener(c),g=!0)};f.stop=function(){g&&(g=!1,a(),chrome.runtime.onMessage.removeListener(c))};
return f};a=null;g("getBgCamSustainService",f)}}});n.register("bg-castify-draw-service",["bg-message-service","bg-storage-service","bg-cam-sustain-service","throttle"],function(g){function f(a,b){return function(){var c=Array.prototype.slice.call(arguments,0);return new Promise(function(e,d){c.push(function(a){chrome.runtime.lastError?d(chrome.runtime.lastError):e(a)});a.apply(b,c)})}}function b(b,f,g){function e(a){var c=[n.executeScript(b,{file:a?E:D,allFrames:!0,matchAboutBlank:!0,runAt:"document_start"})];
a&&c.push(n.insertCSS(b,{file:g,allFrames:!0,matchAboutBlank:!0,runAt:"document_start"}));return Promise.all(c)}function y(){if(!t){var a=e(!0).then(function(){v=n.connect(b,{name:"castifyDraw"});v.onDisconnect.addListener(function(){t===a&&(t=null)});v.onMessage.addListener(function(a){if(w.hasOwnProperty(a.type))w[a.type](v,a.data)});return v});a.catch(function(a){console.error("BgCastifyDrawServiceError",a)});t=a}return t}function l(a){var b,e;return $traceurRuntime.asyncWrap(function(d){for(;;)switch(d.state){case 0:b=
new Promise(function(a){w.initializeDone=function(){w.initializeDone=null;a()}});a=Object.assign({bundlesPath:f},a);d.state=9;break;case 9:Promise.resolve(y()).then(d.createCallback(2),d.errback);return;case 2:Promise.resolve(c().getData()).then(d.createCallback(5),d.errback);return;case 5:e=d.value;d.state=4;break;case 4:C("initialize",{config:a,storage:e});d.state=11;break;case 11:Promise.resolve(b).then(d.createCallback(7),d.errback);return;case 7:w.initializeDone=null;x=void 0;d.state=-2;break;
default:return d.end()}},this)}function k(a){a.tabId==b&&(0===a.frameId?(B.cancel(),r(),l(x)):B())}function A(a){a.replacedTabId===b&&(b=a.tabId,r(),l(x))}function C(a,b){return y().then(function(c){c.postMessage({type:a,data:b})})}function r(){t&&(t.then(function(a){a.disconnect()}),t=null)}var E=f+"content-script.js",D=f+"content-script-frame.js",z={},v,t,w={},x,B=h(function(){e()},1E3);z.initialize=function(a){return $traceurRuntime.asyncWrap(function(b){for(;;)switch(b.state){case 0:x=a;b.state=
5;break;case 5:b.returnValue=l(a);b.state=2;break;case 2:b.state=-2;break;default:return b.end()}},this)};z.dispose=function(){r();chrome.webNavigation.onCommitted.removeListener(k);chrome.webNavigation.onTabReplaced.removeListener(A);a().stop()};d().start();c().start();a().start();y();chrome.webNavigation.onCommitted.addListener(k);chrome.webNavigation.onTabReplaced.addListener(A);return z}var d,c,a,h,n;return{setters:[function(a){d=a.getBgMessageService},function(a){c=a.getBgStorageService},function(b){a=
b.getBgCamSustainService},function(a){h=a.default}],execute:function(){n={executeScript:f(chrome.tabs.executeScript,chrome.tabs),insertCSS:f(chrome.tabs.insertCSS,chrome.tabs),connect:chrome.tabs.connect.bind(chrome.tabs)};g("BgCastifyDrawService",b)}}});n.register("background-exports",["bg-castify-draw-service"],function(g){var f;return{setters:[function(b){f=b.BgCastifyDrawService}],execute:function(){window.BgCastifyDrawService=f}}})});
