(function(l){function k(c,p,b,d){if("string"!=typeof c)throw"System.register provided no module name";p="boolean"==typeof b?{declarative:!1,deps:p,execute:d,executingRequire:b}:{declarative:!0,deps:p,declare:b};p.name=c;c in n||(n[c]=p);c=p.deps;b=[];d=0;for(var e=c.length;d<e;d++)-1==v.call(b,c[d])&&b.push(c[d]);p.deps=b;p.normalizedDeps=p.deps}function f(c,b){b[c.groupIndex]=b[c.groupIndex]||[];if(-1==v.call(b[c.groupIndex],c)){b[c.groupIndex].push(c);for(var d=0,e=c.normalizedDeps.length;d<e;d++){var a=
n[c.normalizedDeps[d]];if(a&&!a.evaluated){var h=c.groupIndex+(a.declarative!=c.declarative);if(void 0===a.groupIndex||a.groupIndex<h){if(void 0!==a.groupIndex&&(b[a.groupIndex].splice(v.call(b[a.groupIndex],a),1),0==b[a.groupIndex].length))throw new TypeError("Mixed dependency cycle detected");a.groupIndex=h}f(a,b)}}}}function a(c){return w[c]||(w[c]={name:c,dependencies:[],exports:{},importers:[]})}function t(c){if(!c.module){var b=c.module=a(c.name),e=c.module.exports,g=c.declare.call(l,function(c,
d){b.locked=!0;e[c]=d;for(var a=0,h=b.importers.length;a<h;a++){var n=b.importers[a];if(!n.locked){var g=v.call(n.dependencies,b);n.setters[g](e)}}b.locked=!1;return d});b.setters=g.setters;b.execute=g.execute;if(!b.setters||!b.execute)throw new TypeError("Invalid System.register form for "+c.name);for(var g=0,f=c.normalizedDeps.length;g<f;g++){var h=c.normalizedDeps[g],q=n[h],r=w[h];r?h=r.exports:q&&!q.declarative?h=q.module.exports&&q.module.exports.__esModule?q.module.exports:{"default":q.module.exports,
__useDefault:!0}:q?(t(q),r=q.module,h=r.exports):h=d(h);r&&r.importers?(r.importers.push(b),b.dependencies.push(r)):b.dependencies.push(null);if(b.setters[g])b.setters[g](h)}}}function b(c){if(!c.module){var a={},m=c.module={exports:a,id:c.name};if(!c.executingRequire)for(var g=0,f=c.normalizedDeps.length;g<f;g++){var h=n[c.normalizedDeps[g]];h&&b(h)}c.evaluated=!0;if(a=c.execute.call(l,function(a){for(var h=0,g=c.deps.length;h<g;h++)if(c.deps[h]==a){a=c.normalizedDeps[h];h=void 0;if(g=n[a])g.declarative?
e(a,[]):g.evaluated||b(g),h=g.module.exports;else if(h=d(a),!h)throw Error("Unable to load dependency "+a+".");a=(!g||g.declarative)&&h&&h.__useDefault?h["default"]:h;return a}throw new TypeError("Module "+a+" not declared as a dependency.");},a,m))m.exports=a}}function e(b,a){var m=n[b];if(m&&!m.evaluated&&m.declarative){a.push(b);for(var g=0,f=m.normalizedDeps.length;g<f;g++){var h=m.normalizedDeps[g];-1==v.call(a,h)&&(n[h]?e(h,a):d(h))}m.evaluated||(m.evaluated=!0,m.module.execute.call(l))}}function d(c){if(u[c])return u[c];
var a=n[c];if(!a)throw"Module "+c+" not present.";var d=n[c];d.groupIndex=0;var g=[];f(d,g);for(var d=!!d.declarative==g.length%2,k=g.length-1;0<=k;k--){for(var h=g[k],q=0;q<h.length;q++){var r=h[q];d?t(r):b(r)}d=!d}e(c,[]);n[c]=void 0;g=a.module.exports;if(!g||!a.declarative&&!0!==g.__esModule)g={"default":g,__useDefault:!0};return u[c]=g}var n={},v=Array.prototype.indexOf||function(b){for(var a=0,d=this.length;a<d;a++)if(this[a]===b)return a;return-1},w={},u={};return function(b,a){var e;e={register:k,
get:d,set:function(b,a){u[b]=a},newModule:function(b){return b},global:l};e.set("@empty",{});a(e);for(e=0;e<b.length;e++)d(b[e])}})("undefined"!=typeof window?window:global)(["cam-frame"],function(l){l.register("platform",[],function(k){var f;return{setters:[],execute:function(){f=window.navigator.userAgent.includes("Macintosh");k("default",{IS_MAC:f,isExtension:!!chrome.runtime.id,isTopFrame:window.top===window})}}});l.register("w69b/async-response",[],function(k){k("createSender",function(f){var a=
{},t=0,b={};a.sendWithResponse=function(a,d){return new Promise(function(n,k){var l=++t;b[l]=[n,k];f({type:a,data:d,msgId:l})})};a.send=function(b,a){f({type:b,data:a})};a.handleResult=function(a){if(a&&"result"===a.type){var d=b[a.msgId];delete b[a.msgId];if(a.hasOwnProperty("error")||a.isError)d[1](a.error);else d[0](a.data);return!0}return!1};return a});k("createRespond",function(f){return function(a,t){Promise.resolve(a).then(function(a){f({type:"result",msgId:t.msgId,data:a})},function(a){f({type:"result",
msgId:t.msgId,error:a,isError:!0})})}});return{setters:[],execute:function(){}}});l.register("w69b/q",[],function(k){var f;return{setters:[],execute:function(){f={defer:function(){var a={};a.promise=new Promise(function(f,b){a.resolve=f;a.reject=b});return a}};f.when=Promise.resolve.bind(Promise);f.all=Promise.all.bind(Promise);f.reject=Promise.reject.bind(Promise);Promise.prototype.finally||(Promise.prototype.finally=function(a){var f=this.constructor;return this.then(function(b){return f.resolve(a()).then(function(){return b})},
function(b){return f.resolve(a()).then(function(){throw b;})})});k("default",f)}}});l.register("chrome-messaging",[],function(k){function f(a){return a instanceof Error?Promise.reject(a.toString()):Promise.reject(a)}k("sendMessage",function(a,f){return new Promise(function(b,e){chrome.runtime.sendMessage({type:a,data:f},function(a){chrome.runtime.lastError?e(chrome.runtime.lastError):a?"result"===a.type?b(a.data):"error"===a.type&&e(a.data):e()})})});k("respond",function(a,k){Promise.resolve(k).catch(f).then(function(b){a({type:"result",
data:b})},function(b){a({type:"error",data:b})})});return{setters:[],execute:function(){}}});l.register("w69b/promise-tool",["w69b/q"],function(k){var f,a;return{setters:[function(a){f=a.default}],execute:function(){a={wrapChromeError:function(a,b){return function(){var e=Array.prototype.slice.call(arguments,0),d=f.defer();e.push(function(a){chrome.runtime.lastError?d.reject(chrome.runtime.lastError):d.resolve(a)});a.apply(b,e);return d.promise}},wrapCallbacks:function(a,b){return function(){var e=
Array.prototype.slice.call(arguments,0),d=f.defer();e.push(d.resolve.bind(d));e.push(d.reject.bind(d));a.apply(b,e);return d.promise}}};k("default",a)}}});l.register("w69b/webrtc",["w69b/promise-tool","w69b/q"],function(k){function f(a){return a.some(function(a){return!!a.label})}var a,l,b,e;return{setters:[function(b){a=b.default},function(a){l=a.default}],execute:function(){b={};e=window.navigator;b.getUserMedia=e.mediaDevices&&e.mediaDevices.getUserMedia?e.mediaDevices.getUserMedia.bind(e.mediaDevices):
a.wrapCallbacks(e.getUserMedia||e.webkitGetUserMedia||e.mozGetUserMedia||e.msGetUserMedia,e);b.getSources=e.mediaDevices&&e.mediaDevices.enumerateDevices?function(){return l.when(e.mediaDevices.enumerateDevices()).then(function(a){return a.filter(function(a){return a.kind.endsWith("input")}).map(function(a){var b={id:a.deviceId,label:a.label};b.kind=a.kind.substring(0,a.kind.length-5);return b})})}:window.MediaStreamTrack&&MediaStreamTrack.getSources?a.wrapCallbacks(MediaStreamTrack.getSources,MediaStreamTrack):
function(){return Promise.resolve([])};b.getSourcesByKind=function(a){return b.getSources().then(function(b){return b.filter(function(b){return b.kind===a})})};b.getVideoSources=function(){return b.getSourcesByKind("video")};b.getAudioSources=function(){return b.getSourcesByKind("audio")};b.hasCamera=function(){return b.getVideoSources().then(function(a){return 0<a.length})};b.hasMicrophone=function(){return b.getAudioSources().then(function(a){return 0<a.length})};b.hasVideoAccess=function(){return b.getVideoSources().then(f)};
b.hasAudioAccess=function(){return b.getAudioSources().then(f)};k("default",b)}}});l.register("cam-frame",["platform","w69b/async-response","w69b/webrtc","chrome-messaging"],function(k){function f(){function f(){c.pause();URL.revokeObjectURL(p);p=null;m.getTracks().forEach(function(a){a.stop()});m=null}function k(a,b,c){return a&&g.hasOwnProperty(a.type)?(e.respond(c,g[a.type](a.data)),!0):!1}function w(a){return a instanceof Error?Promise.reject(a.toString()):Promise.reject(a)}function u(a){a=a.data;
if(g.hasOwnProperty(a.type)){var b=Promise.resolve(g[a.type](a.data)).catch(w);x(b,a)}}var c,p,m,g={start:function(a){m&&f();return b.getUserMedia({video:a}).then(function(a){m=a;a=new Promise(function(a){c||(c=document.createElement("video"),c.volume=0,document.body.appendChild(c));c.addEventListener("canplay",function y(){c.removeEventListener("canplay",y);a({width:c.videoWidth,height:c.videoHeight})})});p=URL.createObjectURL(m);c.src=p;c.play();return a})},stop:function(){f()},getVideoDevices:function(){return b.getVideoSources()}},
x=l.createRespond(function(a){window.parent.postMessage(a,window.location.origin)});a.isExtension?chrome.runtime.onMessage.addListener(k):(console.debug("camFrame: using dev-only messaging"),window.addEventListener("message",u));window.parent.postMessage(d,"*")}var a,l,b,e,d;return{setters:[function(b){a=b.default},function(a){l=a},function(a){b=a.default},function(a){e=a}],execute:function(){d="castifyDrawCamFrameReady";f()}}})});
